// This file is auto-generated by the Supabase Type Generation workflow.
// Do NOT edit manually. Run the "Supabase Type Generation" GitHub Actions
// workflow to regenerate from the live schema.
//
// To regenerate locally (requires SUPABASE_ACCESS_TOKEN env var):
//   npx supabase gen types typescript --project-id bjblfzfdtfvuitqdbodn > src/types/database.types.ts

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  public: {
    Tables: Record<string, never>
    Views: Record<string, never>
    Functions: Record<string, never>
    Enums: Record<string, never>
    CompositeTypes: Record<string, never>
  }
}
